/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.anggaranothing.pakar.dyslexia.client;

/**
 *
 * @author AnggaraNothing
 */
public class FrameLauncher extends javax.swing.JInternalFrame {

    private Thread userThread;
    
    /**
     * Creates new form MenuMain
     */
    public FrameLauncher() {
        initComponents();
    }
    
    private void attachToParent( javax.swing.JInternalFrame frame , boolean isCentered ) {
        Helper.attachToDesktop( (javax.swing.JDesktopPane) this.getParent(), frame, isCentered );
    }
    
    private void checkUserSessionStatus() {
        if( userThread != null && userThread.isAlive() ) return;
        
        userThread = new Thread(new Runnable() { public void run(){
            String text = "Login";
            if( Main.userSession.isUserLogged() ) {
                text = "Logout";
            }
            btnUserLog.setText( text );
        }});
        userThread.start();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jXTaskPaneContainer1 = new org.jdesktop.swingx.JXTaskPaneContainer();
        tskPaneAdmin = new org.jdesktop.swingx.JXTaskPane();
        jPanel1 = new javax.swing.JPanel();
        btnUser = new javax.swing.JButton();
        btnGroup = new javax.swing.JButton();
        tskPaneExpert = new org.jdesktop.swingx.JXTaskPane();
        jPanel2 = new javax.swing.JPanel();
        btnSymptom = new javax.swing.JButton();
        btnDisease = new javax.swing.JButton();
        btnDiagnostic = new javax.swing.JButton();
        btnRelation = new javax.swing.JButton();
        btnLevel = new javax.swing.JButton();
        tskPaneEndUser = new org.jdesktop.swingx.JXTaskPane();
        jPanel3 = new javax.swing.JPanel();
        btnUserLog = new javax.swing.JButton();
        btnStartDiagnostic = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setIconifiable(true);
        setTitle("Launcher");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameDeiconified(evt);
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
        });

        org.jdesktop.swingx.VerticalLayout verticalLayout2 = new org.jdesktop.swingx.VerticalLayout();
        verticalLayout2.setGap(14);
        jXTaskPaneContainer1.setLayout(verticalLayout2);

        tskPaneAdmin.setTitle( "Admin Menu" );
        tskPaneAdmin.setCollapsed( true );

        btnUser.setText("User Data");
        btnUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserActionPerformed(evt);
            }
        });

        btnGroup.setText("Group Data");
        btnGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGroupActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnUser)
                .addGap(18, 18, 18)
                .addComponent(btnGroup)
                .addContainerGap(165, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUser)
                    .addComponent(btnGroup))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tskPaneAdmin.getContentPane().add(jPanel1);

        jXTaskPaneContainer1.add(tskPaneAdmin);

        tskPaneExpert.setTitle( "Expert Menu" );
        tskPaneExpert.setCollapsed( true );

        btnSymptom.setText("Symptom Data");
        btnSymptom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSymptomActionPerformed(evt);
            }
        });

        btnDisease.setText("Disease Data");
        btnDisease.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDiseaseActionPerformed(evt);
            }
        });

        btnDiagnostic.setText("Diagnostic Data");
        btnDiagnostic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDiagnosticActionPerformed(evt);
            }
        });

        btnRelation.setText("Relation Data");
        btnRelation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelationActionPerformed(evt);
            }
        });

        btnLevel.setText("CF Level Data");
        btnLevel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLevelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnLevel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDiagnostic))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnSymptom)
                        .addGap(18, 18, 18)
                        .addComponent(btnDisease)
                        .addGap(18, 18, 18)
                        .addComponent(btnRelation)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSymptom)
                    .addComponent(btnDisease)
                    .addComponent(btnRelation))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDiagnostic)
                    .addComponent(btnLevel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tskPaneExpert.getContentPane().add(jPanel2);

        jXTaskPaneContainer1.add(tskPaneExpert);

        tskPaneEndUser.setTitle( "End-User Menu" );

        btnUserLog.setText("Login");
        btnUserLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserLogActionPerformed(evt);
            }
        });

        btnStartDiagnostic.setText("Start Diagnostic");
        btnStartDiagnostic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartDiagnosticActionPerformed(evt);
            }
        });

        jButton1.setText("Diagnostic History");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnUserLog)
                .addGap(18, 18, 18)
                .addComponent(btnStartDiagnostic)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUserLog)
                    .addComponent(btnStartDiagnostic)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tskPaneEndUser.getContentPane().add(jPanel3);

        jXTaskPaneContainer1.add(tskPaneEndUser);

        jScrollPane1.setViewportView(jXTaskPaneContainer1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserActionPerformed
        // TODO add your handling code here:
        attachToParent( new FrameUser() , true );
    }//GEN-LAST:event_btnUserActionPerformed

    private void btnUserLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserLogActionPerformed
        // TODO add your handling code here:
        if( Main.userSession.isUserLogged() ) {
            Main.doLogout();
            checkUserSessionStatus();
        } else {
            MenuLogin frmMenuLogin = new MenuLogin();
            frmMenuLogin.addWindowListener(new java.awt.event.WindowAdapter() {
                public void windowClosing(java.awt.event.WindowEvent evt) {
                    checkUserSessionStatus();
                }
            });

            Helper.attachToFrame( null, frmMenuLogin, true );
        }
    }//GEN-LAST:event_btnUserLogActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
        checkUserSessionStatus();
    }//GEN-LAST:event_formInternalFrameOpened

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        // TODO add your handling code here:
        checkUserSessionStatus();
    }//GEN-LAST:event_formInternalFrameActivated

    private void formInternalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameDeiconified
        // TODO add your handling code here:
        checkUserSessionStatus();
    }//GEN-LAST:event_formInternalFrameDeiconified

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered
        // TODO add your handling code here:
        checkUserSessionStatus();
    }//GEN-LAST:event_formMouseEntered

    private void formMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseExited
        // TODO add your handling code here:
        checkUserSessionStatus();
    }//GEN-LAST:event_formMouseExited

    private void btnGroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGroupActionPerformed
        // TODO add your handling code here:
        attachToParent( new FrameGroup() , true );
    }//GEN-LAST:event_btnGroupActionPerformed

    private void btnSymptomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSymptomActionPerformed
        // TODO add your handling code here:
        attachToParent( new FrameSymptom() , true );
    }//GEN-LAST:event_btnSymptomActionPerformed

    private void btnDiseaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDiseaseActionPerformed
        // TODO add your handling code here:
        attachToParent( new FrameDisease() , true );
    }//GEN-LAST:event_btnDiseaseActionPerformed

    private void btnLevelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLevelActionPerformed
        // TODO add your handling code here:
        attachToParent( new FrameCfLevel() , true );
    }//GEN-LAST:event_btnLevelActionPerformed

    private void btnDiagnosticActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDiagnosticActionPerformed
        // TODO add your handling code here:
        attachToParent( new FrameDiagnostic() , true );
    }//GEN-LAST:event_btnDiagnosticActionPerformed

    private void btnRelationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelationActionPerformed
        // TODO add your handling code here:
        attachToParent( new FrameRelation() , true );
    }//GEN-LAST:event_btnRelationActionPerformed

    private void btnStartDiagnosticActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartDiagnosticActionPerformed
        // TODO add your handling code here:
        attachToParent( new FrameStartDiagnostic() , true );
    }//GEN-LAST:event_btnStartDiagnosticActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        attachToParent( new FrameDiagnosticHistory() , true );
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDiagnostic;
    private javax.swing.JButton btnDisease;
    private javax.swing.JButton btnGroup;
    private javax.swing.JButton btnLevel;
    private javax.swing.JButton btnRelation;
    private javax.swing.JButton btnStartDiagnostic;
    private javax.swing.JButton btnSymptom;
    private javax.swing.JButton btnUser;
    private javax.swing.JButton btnUserLog;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private org.jdesktop.swingx.JXTaskPaneContainer jXTaskPaneContainer1;
    private org.jdesktop.swingx.JXTaskPane tskPaneAdmin;
    private org.jdesktop.swingx.JXTaskPane tskPaneEndUser;
    private org.jdesktop.swingx.JXTaskPane tskPaneExpert;
    // End of variables declaration//GEN-END:variables
}
