/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.anggaranothing.pakar.dyslexia.client;

import java.awt.event.WindowEvent;
import java.io.IOException;
import java.net.MalformedURLException;
import java.rmi.Naming;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import javax.swing.JOptionPane;

/**
 *
 * @author amikom
 */
public final class MenuConnect extends javax.swing.JFrame {

    private final String rmiRegistryPath = ClientConfig.RMI_USERLOG_NAME;
    /**
     * Creates new form FrmLogin
     */
    public MenuConnect() {
        initComponents();
        
        //Helper.setLocationToCenter( this );
        
        jXBusyLabel1.setVisible(false);
    }

    private void storeConfig() {
        try {
            ClientConfig.update(ClientConfig.INI_RMI_HEADER , ClientConfig.INI_RMI_HOST, txtIpServer.getText() );
            ClientConfig.update(ClientConfig.INI_RMI_HEADER , ClientConfig.INI_RMI_PORT, txtPortServer.getText() );
        } catch (IOException ex) {
            Main.LOGGER.trace( "Client failed to update config file !", ex );
            Helper.logThrowable( "Client failed to update config file !", ex );
        }
    }
    
    private void cobaKonek() {
        jXBusyLabel1.setVisible(true);
        // set lokasi remote object
        String url = String.format( "rmi://%s:%d/%s", ClientConfig.getRmiHost(), ClientConfig.getRmiPort(), rmiRegistryPath );
        boolean isSucceed = false;
        
        try {
            // ambil referensi dari remote object yg ada di server
            Naming.lookup(url);
            isSucceed = true;
            // method akan tereksekusi ketika tidak ada exception (error)
            JOptionPane.showMessageDialog( this,
                "SUCCEED to connect to the server.",
                null, JOptionPane.INFORMATION_MESSAGE );
        } catch (NotBoundException ex) {
            Helper.logThrowable( "Client failed to connect to the server !", ex );
        } catch (MalformedURLException ex) {
            Helper.logThrowable( "Client failed to connect to the server !", ex );
        } catch (RemoteException ex) {
            Helper.ShowDialogAndLogThrowable( this, "Client failed to connect to the server !", ex );
        }
        jXBusyLabel1.setVisible(false);

        if( isSucceed )
            this.dispatchEvent(new WindowEvent( this, WindowEvent.WINDOW_CLOSING ) );
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtIpServer = new javax.swing.JTextField();
        btnSubmit = new javax.swing.JButton();
        jXBusyLabel1 = new org.jdesktop.swingx.JXBusyLabel();
        jLabel2 = new javax.swing.JLabel();
        txtPortServer = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Connect to server...");
        setAlwaysOnTop(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setText("Please enter server host and port...");

        txtIpServer.setText(com.anggaranothing.pakar.dyslexia.client.ClientConfig.getRmiHost());
        txtIpServer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIpServerActionPerformed(evt);
            }
        });

        btnSubmit.setText("Connect");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        jXBusyLabel1.setText("Connecting...");
        jXBusyLabel1.setBusy(true);

        jLabel2.setText(":");

        txtPortServer.setText(String.valueOf( com.anggaranothing.pakar.dyslexia.client.ClientConfig.getRmiPort() ));
        txtPortServer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPortServerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtIpServer, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPortServer, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSubmit))
                    .addComponent(jXBusyLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIpServer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSubmit)
                    .addComponent(jLabel2)
                    .addComponent(txtPortServer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jXBusyLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        storeConfig();
        
        new Thread(new Runnable() {
            public void run(){
                cobaKonek();
            }
        }).start();
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void txtIpServerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIpServerActionPerformed
        // TODO add your handling code here:
        btnSubmit.doClick();
    }//GEN-LAST:event_txtIpServerActionPerformed

    private void txtPortServerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPortServerActionPerformed
        // TODO add your handling code here:
        btnSubmit.doClick();
    }//GEN-LAST:event_txtPortServerActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        Main.frameMap.remove( getClass().getName() );
    }//GEN-LAST:event_formWindowClosing


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private org.jdesktop.swingx.JXBusyLabel jXBusyLabel1;
    private javax.swing.JTextField txtIpServer;
    private javax.swing.JTextField txtPortServer;
    // End of variables declaration//GEN-END:variables
}
